@baseUrl = https://si-app.test/api/app
@token = {{Login.response.body.token}}
@studentNIS = 202103144




############ 
### AUTH ###

# @name Login
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "Admin",
    "password": "password"
}

###

# @name Logout
POST {{baseUrl}}/auth/logout HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}





################
### Students ###

# @name Students
GET {{baseUrl}}/students HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name ShowStudent
GET {{baseUrl}}/students/{{studentNIS}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}