@baseUrl = https://si-app.test/api/santri
@token = {{Login.response.body.data.token}}
@newPlanId = {{StorePlan.response.body.data.id}}





############ 
### AUTH ###

# @name Login
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "192003037",
    "password": "password"
}

###

# @name User
GET {{baseUrl}}/auth/user HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}





############ 
### User ###

# @name Users
GET {{baseUrl}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name FindUser
GET {{baseUrl}}/users/192003037 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}








################
### Plans ###

# @name Plans
GET {{baseUrl}}/plans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StorePlan
POST {{baseUrl}}/plans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Ini Action Plan"
}

###

# @name FindPlan
GET {{baseUrl}}/plans/{{newPlanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdatePlan
PUT {{baseUrl}}/plans/{{newPlanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "ganti judul"
}

###

# @name UpdateDetailPlan
PUT {{baseUrl}}/plans/{{newPlanId}}/detail HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "minor_routine",
    "content": "Ini minor"
}

###

# @name DestroyPlan
DELETE  {{baseUrl}}/plans/{{newPlanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name LatestPlan
GET {{baseUrl}}/plans/latest HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name ClonePlan
POST {{baseUrl}}/plans/10/clone HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}