@baseUrl = https://si-app.test/api/sbt
@token = {{Login.response.body.data.token}}
@studentId = 98
@studentNIS = 192002144
@newNoteId = {{StoreNote.response.body.note.id}}
@planId = 31




############ 
### HOME ###

# @name Home
GET {{baseUrl}}?nis=192002144 HTTP/1.1
Accept: application/json
Content-Type: application/json




############ 
### AUTH ###

# @name Login
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "mukhlis.amrullah",
    "password": "password"
}

###

# @name Logout
POST {{baseUrl}}/auth/logout HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}

###

# @name User
GET {{baseUrl}}/auth/user HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}







################
### Students ###

# @name Students
GET {{baseUrl}}/students HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name ShowStudent
GET {{baseUrl}}/students/{{studentNIS}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name NotesStudent
GET {{baseUrl}}/students/{{studentId}}/notes HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name LatestNoteStudent
GET {{baseUrl}}/students/{{studentId}}/latest-note HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name PlansStudent
GET {{baseUrl}}/students/{{studentId}}/plans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name PlanStudent
GET {{baseUrl}}/students/{{studentId}}/plans/{{planId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name LatestPlanStudent
GET {{baseUrl}}/students/{{studentId}}/latest-plan HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}








################
### Notes ###

# @name Notes
GET {{baseUrl}}/notes HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StoreNote
POST {{baseUrl}}/notes HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 2,
    "title": "Ini Judul Lagi",
    "unit": "TAHFIDZ",
    "note": "Apa aja",
    "type": 0
}

###

# @name FindNote
GET {{baseUrl}}/notes/{{newNoteId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdateNote
PUT {{baseUrl}}/notes/{{newNoteId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 2,
    "note": "Sudah dipudate",
    "type": 0
}

###

# @name DestroyNote
DELETE {{baseUrl}}/notes/{{newNoteId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}