@baseUrl = https://si-app.test/api/sdt
@token = {{Login.response.body.data.token}}
@studentUid = 7452159423019
@newUserId = {{StoreUser.response.body.data.id}}
@newRakId = {{StoreRak.response.body.data.id}}
@newDeviceUid = {{StoreDevice.response.body.data.uid}}
@newLoanId = {{StoreLoan.response.body.loan.id}}


@deviceUID = 0930610483491




############ 
### AUTH ###

# @name Login
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "Amrullah",
    "password": "password"
}

###

# @name Logout
POST {{baseUrl}}/auth/logout HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}

###

# @name User
GET {{baseUrl}}/auth/user HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}






############ 
### User ###

# @name Users
GET {{baseUrl}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StoreUser
POST {{baseUrl}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "user_baru_a",
    "password": "password",
    "role": "operator"
}

###

# @name FindUser
GET {{baseUrl}}/users/{{newUserId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdateUser
PUT {{baseUrl}}/users/{{newUserId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "user_update",
    "role": "admin"
}

###

# @name DestroyUser
DELETE {{baseUrl}}/users/{{newUserId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}






################
### Students ###

# @name Students
GET {{baseUrl}}/students HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name NameOnlyStudent
GET {{baseUrl}}/students/name-only HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name ShowStudent
GET {{baseUrl}}/students/{{studentUid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdateStudent
PUT {{baseUrl}}/students/update HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}






############
### Raks ###

# @name Raks
GET {{baseUrl}}/raks HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StoreRak
POST {{baseUrl}}/raks HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Rak Laptop"
}
###

# @name FindRak
GET {{baseUrl}}/raks/{{newRakId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdateRak
PUT {{baseUrl}}/raks/{{newRakId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Rak Laptop Update"
}

###

# @name DestroyRak
DELETE {{baseUrl}}/raks/{{newRakId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###





################
### Devices ###

# @name Devices
GET {{baseUrl}}/device HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StoreDevice
POST {{baseUrl}}/device HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Asus",
    "uid": "8743245678",
    "type": "1",
    "rak_id": "1"
}

###

# @name ShowDevice
GET {{baseUrl}}/device/{{newDeviceUid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name UpdateDevice
PUT {{baseUrl}}/device/{{newDeviceUid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Samsung",
    "uid": "09306210483491",
    "type": "0",
    "rak_id": "2"
}

###

# @name DestroyDevice
DELETE {{baseUrl}}/device/{{newDeviceUid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name AssignDevice
PUT {{baseUrl}}/device/assign/{{newDeviceUid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": "2"
}

###

# @name TemplateDevice
GET {{baseUrl}}/device/import-template HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name SummaryDevice
GET {{baseUrl}}/device/summary HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###




#############
### Loans ###

# @name Loans
GET {{baseUrl}}/loans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StoreLoan
POST {{baseUrl}}/loans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_uid": "3520895443081",
    "device_uid": "2474923175974",
    "user_id": 2
}

###

# @name FindLoan
GET {{baseUrl}}/loans/{{studentUid}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdateLoan
PUT {{baseUrl}}/loans/{{newLoanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_uid": "3520895443081",
    "device_uid": "2474923175974"
}
###
