@baseUrl = https://si-app.test/api/student
@token = {{Login.response.body.token}}
@newUserId = {{StoreUser.response.body.user.id}}
@newPlanId = {{StorePlan.response.body.plan.id}}





############ 
### AUTH ###

# @name Login
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "192003037",
    "password": "password"
}

###

# @name Logout
POST {{baseUrl}}/auth/logout HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}

###

# @name Profile
GET {{baseUrl}}/auth/profile HTTP/1.1
Accept: application/json
Content-Type: application/json 
Authorization: Bearer {{token}}





############ 
### User ###

# @name Users
GET {{baseUrl}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StoreUser
POST {{baseUrl}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "user_baru_lagi",
    "password": "password"
}

###

# @name FindUser
GET {{baseUrl}}/users/{{newUserId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdateUser
PUT {{baseUrl}}/users/{{newUserId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "user_update",
    "password": "ganti_password"
}

###

# @name DestroyUser
DELETE {{baseUrl}}/users/{{newUserId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}







################
### Plans ###

# @name Plans
GET {{baseUrl}}/plans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name StorePlan
POST {{baseUrl}}/plans HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Ini Action Plan Lagi"
}

###

# @name FindPlan
GET {{baseUrl}}/plans/{{newPlanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name UpdatePlan
PUT {{baseUrl}}/plans/{{newPlanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "mayor_agenda",
    "content": "Ini minor"
}

###

# @name DestroyPlan
DELETE  {{baseUrl}}/plans/{{newPlanId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name LatestPlan
GET {{baseUrl}}/latest-plan HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name CountPlan
GET {{baseUrl}}/count-plan HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}